#!/usr/bin/env python

import sys, re

#
# parse command line:
#
# first argument is URL string
# second argument until separator '--' are concept names
# all arguments left are role names
#

URI = '""'

try:
    # uri used in extatoms
    URI = sys.argv[1]
except IndexError:
    pass
    

# list of concept names
conceptnames = []
# list of role names
rolenames = []

doConcept = True

for arg in sys.argv[2:]:

    if arg == '--': doConcept = False

    elif doConcept: conceptnames.append(arg)

    else: rolenames.append(arg)


# global extatom counter
extatomNo = 0
# fact list
rules = []


# given a DL-atom, it parses the various items and returns a HEX
# Extatom and adds found rules to the rules list
def rewrite_atom(atom):

    inout = atom[3:].split(']')

    inlist = inout[0].split(';')

    input = ""
    input += URI
    input += ','
    input += 'dl_pc_'
    input += str(extatomNo)
    input += ','
    input += 'dl_mc_'
    input += str(extatomNo)
    input += ','
    input += 'dl_pr_'
    input += str(extatomNo)
    input += ','
    input += 'dl_mr_'
    input += str(extatomNo)
    input += ','

    for i in inlist:

        plus = i.split('+=')
        minus = i.split('-=')

        if len(plus) > 1:

            rules.append((extatomNo,'p',
                          '"'+plus[0].strip()+'"',
                          plus[1].strip())
                         )

        elif len(minus) > 1:

            rules.append((extatomNo,'m',
                          '"'+minus[0].strip()+'"',
                          minus[1].strip())
                          )

        else: # query term

            input += '"' + i.strip() + '"'


    output = inout[1]

    type = ""
    if len(output.split(',')) > 1: type = "&dlR"
    else: type = "&dlC"

    return type + '[' + input + ']' + output


# more or less optimal regexpr for finding the dl-atoms
dlatom = re.compile('DL\[[\w\;\_+-= \t]+\]'
                    '\((\")?[\w\_]+(\")?(\,(\")?[\w\_]+(\")?)?\)'
                    )


# process each line of stdin
for line in sys.stdin:

    m = dlatom.finditer(line)
    i = 0 # we're at the beginning of the line

    # process each found dl-atom in this line
    for a in m:

        begin,end = a.span() # dl-atom spans from begin to end in line

        sys.stdout.write(line[i:begin]) # output previous stuff
        sys.stdout.write(rewrite_atom(a.group())) # output rewritten dl-atom

        extatomNo += 1
        i = end # next time start to print prev. stuff from this point


    if i == 0: # there was no dl-atom -> output unmodified line

        sys.stdout.write(line)
        
    else: # output trailing string not containing any dl-atom

        sys.stdout.write(line[i:])


# output collected rules
for x in rules:

    if x[2] in conceptnames:

        print 'dl_' + x[1] + 'c_' + str(x[0]) + '(' + x[2] + ',X) :- ' + x[3] +'(X).'
    
    elif x[2] in rolenames:

        print 'dl_' + x[1] + 'r_' + str(x[0]) + '(' + x[2] + ',X,Y) :- ' + x[3] +'(X,Y).'
