#line 2 "RacerAnswerScanner.cpp"

#line 4 "RacerAnswerScanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyRacerFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::istream* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
/* %endif */

void *yyRaceralloc (yy_size_t  );
void *yyRacerrealloc (void *,yy_size_t  );
void yyRacerfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int RacerFlexLexer::yylex()

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[189] =
    {   0,
        0,    0,    7,    7,    0,    0,    3,    3,    5,    5,
        0,    0,   22,   20,   18,   19,   20,   20,    7,    7,
        8,   21,   18,   11,   13,   21,   16,   14,   14,   14,
       21,    3,    3,    4,    6,    6,    5,    5,   21,   18,
       19,    0,    0,    7,    7,   16,   14,    0,   14,   12,
       14,   10,    0,    3,    3,    5,    5,    0,   17,    0,
        0,   12,   12,    0,   12,   12,   12,   14,    0,    0,
        0,    0,   12,   12,    0,   12,    0,   12,    0,   12,
       12,   12,    0,   12,    9,   15,    0,    0,   12,    0,
       12,    0,   12,    0,   12,    0,   12,   12,   12,   12,

       12,   12,   12,   12,    0,    0,    1,    0,   12,    0,
       12,    0,   12,    0,   12,   12,   12,   12,   12,   12,
        0,   12,   12,   12,    0,   12,   12,   12,   12,   12,
       12,    2,    0,    0,   12,   12,   12,   12,    0,    0,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,    6,    6,    9,
        9,    9,   11,   11,   12,   13,   14,   15,   16,   17,
       18,   18,   19,   20,   20,   20,   20,   21,    6,    1,
        6,    1,   22,   23,   24,   25,   25,   25,   26,   25,
       27,   27,   28,   27,   27,   29,   27,   30,   31,   27,
       27,   32,   33,   34,   27,   27,   35,   27,   27,   27,
        1,   36,    1,    1,   37,    1,   38,   25,   25,   25,

       39,   25,   27,   27,   40,   27,   27,   41,   27,   42,
       43,   27,   27,   44,   45,   46,   27,   27,   47,   27,
       27,   27,    1,   48,    1,   49,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[50] =
    {   0,
        1,    2,    1,    1,    2,    3,    4,    5,    3,    6,
        7,    8,    8,    6,    9,    9,    9,    9,    9,    9,
        7,    3,    3,   10,   10,   10,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    1,    6,   10,   10,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    3
    } ;

static yyconst flex_int16_t yy_base[232] =
    {   0,
        0,    4,    8,    9,   25,    0,   15,   16,   73,   92,
       74,   75,  244, 1073,   81, 1073,  236,   61,    0,   93,
     1073, 1073,   99, 1073, 1073,   98,  104,  115,  117,  123,
      209,    0,  100, 1073, 1073,  101,  130,  150,  211,  132,
     1073,   54,  109,    0,  137,  156,    0,  191,  116,  171,
      118, 1073,  175,    0,  138,  159,  181,  205, 1073,  115,
      118,  196,  214,    0,    0,  232,  250,  181,  154,  142,
      148,  160,  268,  286,    0,    0,    0,  304,    0,    0,
      322,  340,    0,    0, 1073, 1073,  187,  183,  358,    0,
        0,    0,  376,    0,  394,    0,    0,  412,  176,  232,

      250,  268,  430,  448,    0,  190, 1073,    0,  466,    0,
        0,    0,  484,    0,    0,  286,  304,  340,  358,  502,
        0,    0,  512,  527,    0,    0,  174,  376,  394,  412,
      537, 1073,    0,    0,  171,  466,  484,  502,    0,    0,
      527,  545,  553,  561,  567,  573,  581,  589,  597,  120,
      604,  612,  620,   11,  628,  636,  644,  650,  658,  666,
      674,  679,  687,  695,  703,    6,  710,  718,  726,    0,
      732,  738,  744,  750,  758,  766,  774,  779,  785,  214,
        0,  791,  797,  803,  809,  815,  821, 1073,  840,  850,
      860,  870,  880,  890,  895,  905,  914,  923,  928,  932,

      940,  950,  958,  960,  968,  976,  984,  986,  988,  990,
      998, 1000, 1002, 1004, 1012, 1014, 1016, 1024, 1032, 1040,
     1042, 1044, 1046, 1048, 1050, 1052, 1054, 1056, 1058, 1060,
     1062
    } ;

static yyconst flex_int16_t yy_def[232] =
    {   0,
      189,  189,  190,  190,  188,    5,  191,  191,  192,  192,
      193,  193,  188,  188,  188,  188,  188,  188,  194,  194,
      188,  188,  188,  188,  188,  188,  188,  195,  195,   29,
      188,  196,  196,  188,  188,  188,  197,  188,  198,  188,
      188,  188,  188,  194,  194,  188,  199,  200,   29,  201,
       29,  188,  202,  196,  196,  197,  188,  198,  188,  188,
      188,  201,  203,  204,   62,  205,  206,   29,  202,  202,
      188,  188,  207,  203,  208,   74,  209,  205,  210,   78,
      211,  206,  212,   82,  188,  188,  188,  188,  207,  213,
       89,  214,  215,  216,  211,  217,   95,  218,   95,   95,

       95,   95,  219,  220,  221,  188,  188,  222,  215,  223,
      109,  224,  218,  225,  113,   95,   95,   95,   95,  219,
      226,  120,  120,  220,  227,  124,  124,  124,  124,  124,
      109,  188,  228,  229,   95,   95,   95,   95,  230,  231,
      124,  124,  124,  124,  109,   95,   95,   95,   95,  124,
      124,  124,  124,   95,   95,   95,   95,  124,  124,  124,
      124,   95,   95,   95,   95,  124,  124,  124,  124,   95,
       95,   95,   95,  124,  124,  124,  124,   95,   95,   95,
      124,  124,  124,  124,  124,  124,  124,    0,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,

      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188
    } ;

static yyconst flex_int16_t yy_nxt[1123] =
    {   0,
      188,   15,   16,   17,   15,   15,   16,   17,   15,   20,
       20,  188,   20,   20,   21,   21,   33,   33,  174,   33,
       33,   34,   34,  162,   18,   22,   23,   22,   22,   23,
       22,   24,   22,   25,   22,   22,   26,   22,   22,   27,
       27,   27,   27,   27,   27,   22,   25,   22,   28,   28,
       28,   28,   28,   28,   29,   28,   28,   28,   30,   28,
       31,   22,   28,   28,   28,   28,   29,   28,   28,   28,
       30,   28,   25,   22,   36,   23,   23,   37,   23,   23,
       39,   39,   40,   60,   42,   40,   43,   38,   38,   38,
       38,   38,   38,   36,   45,   60,   37,   45,   42,   43,

       40,   55,   40,   40,   55,   40,   38,   38,   38,   38,
       38,   38,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   47,   48,   47,   48,   47,   52,
       47,   40,  158,   40,   56,   50,   40,   50,   45,   55,
       61,   45,   55,   49,   51,   49,   68,   71,   86,   72,
       49,   47,   61,   47,   57,   49,   51,   49,   68,   71,
       40,   72,   49,   56,   57,   57,   57,   57,   57,   57,
       46,   46,   46,   46,   46,   46,   62,   70,   63,   62,
       64,   62,   87,  146,   66,   57,  141,   85,  116,   70,
       88,   62,   67,   62,   87,   57,   57,   57,   57,   57,

       57,   62,   88,   63,   62,   64,   62,   59,   49,   73,
       70,   50,  106,   59,  107,   53,   62,   67,   62,   74,
       49,  132,   74,   75,   74,  106,  107,   74,  170,  170,
      170,  170,  170,  132,   74,   74,   74,   78,   41,   63,
       78,   79,   78,  188,  116,   81,  117,  117,  117,  117,
      117,  117,   78,   67,   78,   82,  188,   63,   82,   83,
       82,  188,  116,   82,  118,  118,  118,  118,  119,   99,
       82,   82,   82,   89,  188,   63,   89,   90,   89,  188,
      116,   73,   99,   99,   99,   99,   99,   99,   89,   67,
       89,   74,  188,  188,   74,   75,   74,  188,  188,   74,

      135,  136,  137,  138,  138,  138,   74,   74,   74,   78,
      188,   63,   78,   79,   78,  188,  116,   93,   99,   99,
       99,   99,   99,   99,   78,   67,   78,   95,  188,   63,
       95,   96,   95,  188,  188,   98,   99,  100,  101,  102,
      102,  102,  103,   67,  104,   82,  188,   63,   82,   83,
       82,  188,  116,   82,   99,   99,   99,   99,   99,   99,
       82,   82,   82,   89,  188,   63,   89,   90,   89,  188,
      116,   73,   99,   99,   99,   99,   99,  188,   89,   67,
       89,  109,  188,   63,  109,  110,  109,  188,  141,   93,
      142,  142,  142,  142,  142,  142,  109,   67,  109,   95,

      188,   63,   95,   96,   95,  188,  141,   98,  143,  143,
      143,  143,  144,  127,  103,   67,  104,  113,  188,   63,
      113,  114,  113,  188,  141,   98,  127,  127,  127,  127,
      127,  127,  113,   67,  113,  120,  188,   63,  120,  121,
      120,  188,  188,   98,  123,  123,  123,  123,  123,  123,
      120,   67,  104,  124,  188,   63,  124,  125,  124,  188,
      188,   98,  127,  128,  129,  130,  130,  130,  131,   67,
      109,  109,  188,   63,  109,  110,  109,  188,  146,   93,
      147,  147,  147,  147,  147,  147,  109,   67,  109,  113,
      188,   63,  113,  114,  113,  188,  146,   98,  148,  148,

      148,  148,  149,  135,  113,   67,  113,  120,  188,   63,
      120,  121,  120,  188,  146,   93,  135,  135,  135,  135,
      135,  135,  120,   67,  104,   98,  123,  123,  123,  123,
      123,  123,  124,  188,   63,  124,  125,  124,  188,  188,
       98,  150,  151,  152,  153,  153,  153,  131,   67,  109,
       98,  145,  145,  145,  145,  145,  145,  141,  188,  127,
      127,  127,  127,  127,  127,  141,  188,  127,  127,  127,
      127,  127,  127,  141,  188,  127,  127,  127,  127,  127,
       98,  145,  145,  145,  145,  145,  145,  154,  155,  156,
      157,  157,  157,  146,  188,  135,  135,  135,  135,  135,

      135,  146,  188,  135,  135,  135,  135,  135,  135,  146,
      188,  135,  135,  135,  135,  135,  158,  188,  159,  159,
      159,  159,  159,  159,  158,  188,  160,  160,  160,  160,
      161,  150,  158,  188,  150,  150,  150,  150,  150,  150,
      162,  188,  163,  163,  163,  163,  163,  163,  162,  188,
      164,  164,  164,  164,  165,  154,  162,  188,  154,  154,
      154,  154,  154,  154,  166,  167,  168,  169,  169,  169,
      158,  188,  150,  150,  150,  150,  150,  150,  158,  188,
      150,  150,  150,  150,  150,  150,  158,  188,  150,  150,
      150,  150,  150,  170,  171,  172,  173,  173,  173,  162,

      188,  154,  154,  154,  154,  154,  154,  162,  188,  154,
      154,  154,  154,  154,  154,  162,  188,  154,  154,  154,
      154,  154,  174,  188,  175,  175,  175,  175,  175,  175,
      174,  188,  176,  176,  176,  176,  177,  166,  174,  188,
      166,  166,  166,  166,  166,  166,  178,  178,  178,  178,
      178,  178,  179,  179,  179,  179,  180,  170,  170,  170,
      170,  170,  170,  170,  181,  182,  183,  184,  184,  184,
      174,  188,  166,  166,  166,  166,  166,  166,  174,  188,
      166,  166,  166,  166,  166,  166,  174,  188,  166,  166,
      166,  166,  166,  170,  170,  170,  170,  170,  170,  170,

      170,  170,  170,  170,  170,  185,  185,  185,  185,  185,
      185,  186,  186,  186,  186,  187,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       44,   44,   44,  188,   44,   44,   44,   44,   44,   44,

       49,   49,   49,   49,   49,   54,   54,   54,  188,   54,
       54,   54,   54,   54,   54,   57,  188,  188,  188,  188,
      188,  188,   57,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   47,  188,   47,   47,   47,   48,   48,
       48,   48,   65,  188,   65,   65,   65,   65,   65,   65,
       69,   69,   69,  188,   69,   69,   69,   69,   69,   69,
       76,  188,  188,   76,   76,   76,   76,   76,   77,   77,
       80,  188,   80,   80,   80,   80,   80,   80,   84,  188,
       84,   84,   84,   84,   84,   84,   91,  188,   91,   91,
       91,   91,   91,   91,   92,   92,   62,   62,   94,   94,

       97,  188,   97,   97,   97,   97,   97,   97,  105,  105,
      108,  108,   74,   74,  111,  188,  111,  111,  111,  111,
      111,  111,   78,   78,  112,  112,  115,  188,  115,  115,
      115,  115,  115,  115,  122,  188,  122,  122,  122,  122,
      122,  122,  126,  188,  126,  126,  126,  126,  126,  126,
       82,   82,   89,   89,  133,  133,   95,   95,  134,  134,
      139,  139,  140,  140,  109,  109,  113,  113,  120,  120,
      124,  124,   13,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,

      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188
    } ;

static yyconst flex_int16_t yy_chk[1123] =
    {   0,
        0,    1,    1,    1,    1,    2,    2,    2,    2,    3,
        4,    0,    3,    4,    3,    4,    7,    8,  166,    7,
        8,    7,    8,  154,    2,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    9,   11,   12,    9,   11,   12,
       11,   12,   15,   42,   18,   15,   18,    9,    9,    9,
        9,    9,    9,   10,   20,   42,   10,   20,   18,   18,

       23,   33,   36,   23,   33,   36,   10,   10,   10,   10,
       10,   10,   26,   26,   26,   26,   26,   26,   27,   27,
       27,   27,   27,   27,   28,   28,   29,   29,   28,   30,
       29,   37,  150,   40,   37,   28,   40,   29,   45,   55,
       43,   45,   55,   49,   29,   51,   51,   60,   70,   61,
       30,   28,   43,   29,   38,   49,   29,   51,   51,   60,
       56,   61,   30,   56,   38,   38,   38,   38,   38,   38,
       46,   46,   46,   46,   46,   46,   50,   70,   50,   50,
       50,   50,   71,  135,   50,   57,  127,   68,   99,   69,
       72,   50,   50,   50,   71,   57,   57,   57,   57,   57,

       57,   62,   72,   62,   62,   62,   62,   58,   68,   62,
       53,   48,   87,   39,   88,   31,   62,   62,   62,   63,
       68,  106,   63,   63,   63,   87,   88,   63,  180,  180,
      180,  180,  180,  106,   63,   63,   63,   66,   17,   66,
       66,   66,   66,   13,  100,   66,  100,  100,  100,  100,
      100,  100,   66,   66,   66,   67,    0,   67,   67,   67,
       67,    0,  101,   67,  101,  101,  101,  101,  101,  101,
       67,   67,   67,   73,    0,   73,   73,   73,   73,    0,
      102,   73,  102,  102,  102,  102,  102,  102,   73,   73,
       73,   74,    0,    0,   74,   74,   74,    0,    0,   74,

      116,  116,  116,  116,  116,  116,   74,   74,   74,   78,
        0,   78,   78,   78,   78,    0,  117,   78,  117,  117,
      117,  117,  117,  117,   78,   78,   78,   81,    0,   81,
       81,   81,   81,    0,    0,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   82,    0,   82,   82,   82,
       82,    0,  118,   82,  118,  118,  118,  118,  118,  118,
       82,   82,   82,   89,    0,   89,   89,   89,   89,    0,
      119,   89,  119,  119,  119,  119,  119,    0,   89,   89,
       89,   93,    0,   93,   93,   93,   93,    0,  128,   93,
      128,  128,  128,  128,  128,  128,   93,   93,   93,   95,

        0,   95,   95,   95,   95,    0,  129,   95,  129,  129,
      129,  129,  129,  129,   95,   95,   95,   98,    0,   98,
       98,   98,   98,    0,  130,   98,  130,  130,  130,  130,
      130,  130,   98,   98,   98,  103,    0,  103,  103,  103,
      103,    0,    0,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  104,    0,  104,  104,  104,  104,    0,
        0,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  109,    0,  109,  109,  109,  109,    0,  136,  109,
      136,  136,  136,  136,  136,  136,  109,  109,  109,  113,
        0,  113,  113,  113,  113,    0,  137,  113,  137,  137,

      137,  137,  137,  137,  113,  113,  113,  120,    0,  120,
      120,  120,  120,    0,  138,  120,  138,  138,  138,  138,
      138,  138,  120,  120,  120,  123,  123,  123,  123,  123,
      123,  123,  124,    0,  124,  124,  124,  124,    0,    0,
      124,  141,  141,  141,  141,  141,  141,  124,  124,  124,
      131,  131,  131,  131,  131,  131,  131,  142,    0,  142,
      142,  142,  142,  142,  142,  143,    0,  143,  143,  143,
      143,  143,  143,  144,    0,  144,  144,  144,  144,  144,
      145,  145,  145,  145,  145,  145,  145,  146,  146,  146,
      146,  146,  146,  147,    0,  147,  147,  147,  147,  147,

      147,  148,    0,  148,  148,  148,  148,  148,  148,  149,
        0,  149,  149,  149,  149,  149,  151,    0,  151,  151,
      151,  151,  151,  151,  152,    0,  152,  152,  152,  152,
      152,  152,  153,    0,  153,  153,  153,  153,  153,  153,
      155,    0,  155,  155,  155,  155,  155,  155,  156,    0,
      156,  156,  156,  156,  156,  156,  157,    0,  157,  157,
      157,  157,  157,  157,  158,  158,  158,  158,  158,  158,
      159,    0,  159,  159,  159,  159,  159,  159,  160,    0,
      160,  160,  160,  160,  160,  160,  161,    0,  161,  161,
      161,  161,  161,  162,  162,  162,  162,  162,  162,  163,

        0,  163,  163,  163,  163,  163,  163,  164,    0,  164,
      164,  164,  164,  164,  164,  165,    0,  165,  165,  165,
      165,  165,  167,    0,  167,  167,  167,  167,  167,  167,
      168,    0,  168,  168,  168,  168,  168,  168,  169,    0,
      169,  169,  169,  169,  169,  169,  171,  171,  171,  171,
      171,  171,  172,  172,  172,  172,  172,  172,  173,  173,
      173,  173,  173,  173,  174,  174,  174,  174,  174,  174,
      175,    0,  175,  175,  175,  175,  175,  175,  176,    0,
      176,  176,  176,  176,  176,  176,  177,    0,  177,  177,
      177,  177,  177,  178,  178,  178,  178,  178,  178,  179,

      179,  179,  179,  179,  179,  182,  182,  182,  182,  182,
      182,  183,  183,  183,  183,  183,  183,  184,  184,  184,
      184,  184,  184,  185,  185,  185,  185,  185,  185,  186,
      186,  186,  186,  186,  186,  187,  187,  187,  187,  187,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      194,  194,  194,    0,  194,  194,  194,  194,  194,  194,

      195,  195,  195,  195,  195,  196,  196,  196,    0,  196,
      196,  196,  196,  196,  196,  197,    0,    0,    0,    0,
        0,    0,  197,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  199,    0,  199,  199,  199,  200,  200,
      200,  200,  201,    0,  201,  201,  201,  201,  201,  201,
      202,  202,  202,    0,  202,  202,  202,  202,  202,  202,
      203,    0,    0,  203,  203,  203,  203,  203,  204,  204,
      205,    0,  205,  205,  205,  205,  205,  205,  206,    0,
      206,  206,  206,  206,  206,  206,  207,    0,  207,  207,
      207,  207,  207,  207,  208,  208,  209,  209,  210,  210,

      211,    0,  211,  211,  211,  211,  211,  211,  212,  212,
      213,  213,  214,  214,  215,    0,  215,  215,  215,  215,
      215,  215,  216,  216,  217,  217,  218,    0,  218,  218,
      218,  218,  218,  218,  219,    0,  219,  219,  219,  219,
      219,  219,  220,    0,  220,  220,  220,  220,  220,  220,
      221,  221,  222,  222,  223,  223,  224,  224,  225,  225,
      226,  226,  227,  227,  228,  228,  229,  229,  230,  230,
      231,  231,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,

      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188
    } ;

static yyconst flex_int16_t yy_rule_linenum[21] =
    {   0,
      126,  127,  132,  133,  140,  141,  148,  154,  161,  162,
      163,  165,  170,  172,  177,  182,  192,  203,  205,  207
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "RacerAnswerScanner.lpp"
/* dlvhex-dlplugin -- Integration of Answer-Set Programming and Description Logics.
 *
 * Copyright (C) 2005, 2006, 2007  Thomas Krennwallner
 * 
 * This file is part of dlvhex-dlplugin.
 *
 * dlvhex-dlplugin is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dlvhex-dlplugin is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with dlvhex-dlplugin; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
/**
 * @file   RacerAnswerScanner.lpp
 * @author Thomas Krennwallner
 * @date   Fri Mar 17 21:57:18 2006
 * 
 * @brief  Defines RacerFlexLexer::yylex() method.
 * 
 * @todo   Add Host IP stuff to URI regex.
 */
#line 34 "RacerAnswerScanner.lpp"
#include <iostream>
#include <sstream>
#include <string>

// for yy::location 
#include "RacerAnswerParser.hpp"
#include "RacerAnswerDriver.h"
#include "RacerFlexLexer.h"

using namespace std;

// keep the RacerFlexLexer as close as possible to the C version
#define yylval (*(yy::RacerAnswerParser::semantic_type*)lexval)
#define yylloc ((yy::RacerAnswerParser::location_type*)lexloc)
#define driver (*lexdrv)
#line 63 "RacerAnswerScanner.lpp"
// the following URI regexp is accourding to the ABNF syntax of URIs
// in http://www.ietf.org/rfc/rfc3986.txt

///@todo HOST is not complete, IP-Literal (IPv6 stuff) is missing

#line 110 "RacerAnswerScanner.lpp"
// advance the end location after each tokenizing step
#define YY_USER_ACTION  yylloc->columns(yyleng);
#line 868 "RacerAnswerScanner.cpp"

#define INITIAL 0
#define racererror 1
#define raceranswer 2
#define eatanswerfudge 3
#define eaterrorfudge 4
#define answertrailer 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 114 "RacerAnswerScanner.lpp"



// set begin location to the end location
yylloc->step();



  // abbreviate it as token
  typedef yy::RacerAnswerParser::token token;


#line 1046 "RacerAnswerScanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin = & std::cin;
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout = & std::cout;
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 189 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 188 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 21 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 21 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 22 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 126 "RacerAnswerScanner.lpp"
BEGIN(eaterrorfudge); return token::ERROR;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 127 "RacerAnswerScanner.lpp"
BEGIN(eatanswerfudge); return token::ANSWER;
	YY_BREAK

case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 132 "RacerAnswerScanner.lpp"
/* eat non-" chars */ yylloc->step();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 133 "RacerAnswerScanner.lpp"
BEGIN(raceranswer); yylloc->step();
	YY_BREAK


case 5:
YY_RULE_SETUP
#line 140 "RacerAnswerScanner.lpp"
/* eat all numbers and blanks */ yylloc->step();
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 141 "RacerAnswerScanner.lpp"
BEGIN(racererror); yyless(0);
	YY_BREAK


case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 148 "RacerAnswerScanner.lpp"
{
    // this is the error message
    yylval.sval = new std::string(yytext);
    return token::STRING;
  }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 154 "RacerAnswerScanner.lpp"
BEGIN(answertrailer); yyless(0);
	YY_BREAK


case 9:
YY_RULE_SETUP
#line 161 "RacerAnswerScanner.lpp"
BEGIN(answertrailer); return token::NIL;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 162 "RacerAnswerScanner.lpp"
BEGIN(answertrailer); return token::TRUE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 163 "RacerAnswerScanner.lpp"
BEGIN(answertrailer); yylloc->step();
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 165 "RacerAnswerScanner.lpp"
{
     yylval.sval = new std::string(yytext);
     return token::URI;
  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 170 "RacerAnswerScanner.lpp"
return yy::RacerAnswerParser::token_type(*yytext);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 172 "RacerAnswerScanner.lpp"
{
    yylval.sval = new std::string(yytext);
    return token::STRING;
  }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 177 "RacerAnswerScanner.lpp"
{
    yylval.sval = new std::string(yytext + 2, yyleng - 4); // skip \"
    return token::STRING;
  }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 182 "RacerAnswerScanner.lpp"
{
    std::istringstream(yytext) >> yylval.ival;
    return token::NUMBER; 
  }
	YY_BREAK


case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 192 "RacerAnswerScanner.lpp"
{
    // get the warning message
    BEGIN(INITIAL);
    yylval.sval = new std::string(yytext + 1, yyleng - 3); // skip "\n
    yyless(yyleng - 1); // add \n into the stream
    return token::STRING;
  }
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 203 "RacerAnswerScanner.lpp"
/* skip blanks */ yylloc->step();
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 205 "RacerAnswerScanner.lpp"
yylloc->lines(1); return yy::RacerAnswerParser::token_type(*yytext);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 207 "RacerAnswerScanner.lpp"
driver.error(*yylloc, "invalid character");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 209 "RacerAnswerScanner.lpp"
ECHO;
	YY_BREAK
#line 1299 "RacerAnswerScanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(racererror):
case YY_STATE_EOF(raceranswer):
case YY_STATE_EOF(eatanswerfudge):
case YY_STATE_EOF(eaterrorfudge):
case YY_STATE_EOF(answertrailer):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyRacerfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyRacerfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyRacerrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyRacerrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 189 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 189 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 188);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, register char* yy_bp)
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream* input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyRaceralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyRaceralloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyRacerfree((void *) b->yy_ch_buf  );

	yyRacerfree((void *) b  );
}

/* %if-c-only */
/* %endif */

/* %if-c++-only */

extern "C" int isatty (int );

/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyRaceralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyRacerrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyRaceralloc(new_size  );

		else
			(yy_start_stack) = (int *) yyRacerrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyRaceralloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyRacerrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyRacerfree (void * ptr )
{
	free( (char *) ptr );	/* see yyRacerrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 209 "RacerAnswerScanner.lpp"




// Local Variables:
// mode: C++
// End:

